# Generated by Django 5.0.2 on 2024-03-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_priceupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceupdate',
            old_name='date',
            new_name='dates',
        ),
    ]
