# Generated by Django 5.0.2 on 2024-03-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_date_priceupdate_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
