# Generated by Django 5.0.2 on 2024-03-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tracking', models.BooleanField(default=False, verbose_name='Is Tracking Active')),
            ],
            options={
                'verbose_name_plural': 'Tracking Status',
            },
        ),
    ]
