# Generated by Django 5.0.3 on 2024-03-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_userproductnotification_products_notify_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='notify_users',
        ),
        migrations.DeleteModel(
            name='UserProductNotification',
        ),
    ]
